import { Open_Sans } from "next/font/google";
import "./globals.css";

const open_sans = Open_Sans({ subsets: ["latin"], weight:['400','500','800'], style: "normal"});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
      <main className="max-w-4xl mx-auto p-4">
      {children}
      </main>
      </body>
    </html>
  );
}
